apiVersion: ibm.com/v1
kind: IBMApplicationGateway
metadata:
  name: iag-tools
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  replicas: {{.Values.replicas}}
  deployment:
    serviceAccountName: ibm-application-gateway
    image: ibmcom/ibm-application-gateway:21.12.1
    imagePullPolicy: IfNotPresent 
  configuration:
    - type: configmap
      name: iag-tools-proxy-config
      dataKey: config
    - type: literal 
      value: |
        version: {{.Values.version}}
        server:
            local_applications:
              cred_viewer:
                path_segment: "cred-viewer"
                enable_html: true
