kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iag-tools
  labels:
    app: iag-tools
    chart: iag-tools-chart
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: ibm-application-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iag-tools
